### ISSUE TITLE
User can access the search page even before logging in.

### ISSUE THREAD

**Issue by aditya-mallakula** [CookbookCompass/webweavers#2]
Search page can be accessed even if the user doesn't login.

Steps to reproduce:
1. Open the homepage.
2. Click the Search link.
3. Observe.

Actual Result:
User is taken to the search page.

Expected result:
User should be taken to the login page.

**Comment by korrapati-SaiSree** [comment]
If the user is not logged in, user will be navigated to login page as expected, (not to search page)
