### ISSUE TITLE
Fields on the login and registration pages are missing error handling.

### ISSUE THREAD

**Issue by aditya-mallakula** [CookbookCompass/webweavers#3]
Error handling is missing for the fields on the login and registration pages.

Steps to reproduce:
1. Open the login page.
2. Enter the email in an incorrect format.
3. Observe.
4. Open the registration page.
5. Enter email, password & username in an incorrect format.
6. Observe.

Actual result:
Steps 3 & 6: Error handling is missing.

Expected result:
Steps 3 & 6: Error handling should be present for all available fields.

**Comment by IckyWuv** [comment]
Error handling has been implemented and all known errors have been addressed.
