### ISSUE TITLE
User is able to register using a duplicate username and email id.

### ISSUE THREAD

**Issue by aditya-mallakula** [CookbookCompass/webweavers#8]
When the user registers using an email id or user that has already been used, the registration completes successfully.

Pre condition:
1. Username and email id exist in database.
2. User is on registration page.

Steps to reproduce:
1. Type a username and email id that already exist in the database.
2. Submit the registration form.
3. Observe.

Actual result:
Registration is successful.

Expected result:
An error message should be thrown and the registration should not be completed.

**Comment by IckyWuv** [comment]
Registration will not be complete if a duplicate username and/or email, will warn the user of the duplication, and will redirect back to the registration page.
